STATE_BYTES = 32
AUTH_KEY_BYTES = 32
SESSION_KEY_BYTES = 32
DTI_BYTES = 16
NONCE_BYTES = 16
TAG_BYTES = 16
HKDF_OUTPUT_BYTES = STATE_BYTES + AUTH_KEY_BYTES + SESSION_KEY_BYTES

LABEL_DTI = b"DTI-R/v1/DTI"
LABEL_FAR = b"DTI-R/v1/FAR"
LABEL_BAR = b"DTI-R/v1/BAR"
LABEL_AKA = b"DTI-R/v1/AKA"
LABEL_SALT = b"SALT"
LABEL_KEY_SCHEDULE = b"KEY-SCHEDULE"
